# configuration file for pre-commit and pre-commit.ci
# https://docs.plasmapy.org/en/latest/contributing/pre-commit.html

ci:  # https://pre-commit.ci/#configuration
  autofix_prs: false
  autoupdate_schedule: monthly
  # skip hooks that require network access, which pre-commit.ci forbids
  skip: [uv-lock]

repos:  # https://pre-commit.com/#adding-pre-commit-plugins-to-your-project

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-ast
    name: validate Python code
  - id: trailing-whitespace
    exclude: .*\.py  # use ruff format instead
  - id: end-of-file-fixer
    exclude: .*\.py
  - id: check-merge-conflict
  - id: check-case-conflict
  - id: check-illegal-windows-names
  - id: name-tests-test
    args: [--pytest-test-first]
    exclude: src/plasmapy/tests/_helpers/.*
  - id: detect-private-key
  - id: fix-byte-order-marker
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: forbid-submodules
  - id: check-json
  - id: check-toml
  - id: check-yaml

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.15.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.34.1
  hooks:
  - id: check-github-workflows

- repo: https://github.com/sirosen/texthooks
  rev: 0.7.1
  hooks:
  - id: fix-smartquotes
  - id: fix-spaces
  - id: fix-ligatures
  - id: forbid-bidi-controls

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
  - id: text-unicode-replacement-char

- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
  - id: codespell
    name: codespell (add false positives to pyproject.toml)
    args: [--write-changes]
    exclude: CITATION.cff

- repo: https://github.com/adhtruong/mirrors-typos
  # use mirrors-typos because `pre-commit autoupdate` drops the version
  # of the primary typos repo from v1.x.y to v1
  rev: v1.38.1
  hooks:
  - id: typos
    name: typos (add false positives to _typos.toml)
    exclude: CITATION.cff|docs/notebooks/dispersion/stix_dispersion.ipynb

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.2
  hooks:
  - id: ruff-check
    name: ruff-check (see https://docs.astral.sh/ruff/rules)
    args: [--fix]
  - id: ruff-format

- repo: https://github.com/abravalheri/validate-pyproject
  rev: v0.24.1
  hooks:
  - id: validate-pyproject
    name: validate pyproject.toml
    additional_dependencies: ['validate-pyproject-schema-store[all]']

- repo: https://github.com/tox-dev/pyproject-fmt
  rev: v2.11.0
  hooks:
  - id: pyproject-fmt
    name: format pyproject.toml

- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.9.6
  hooks:
    # running uv lock requires network access or a warm cache, so it
    # cannot be run via pre-commit.ci, even with the `--offline`,
    # `--no-index`, and/or `--check` flags
  - id: uv-lock
    name: uv-lock (skipped in CI)

- repo: https://github.com/hukkin/mdformat
  rev: 1.0.0
  hooks:
  - id: mdformat
    name: format .md files
    # skip wrapping line length to preserve semantic line breaks and
    # avoid messing up GitHub formatting of files in .github/content
    exclude: licenses/.*|LICENSE.md|PATENT.md
    additional_dependencies:
    - mdformat-footnote
    - mdformat-gfm
    - mdformat-gfm-alerts
    - mdformat-ruff
