[build-system]
build-backend = "uv_build"
requires = [ "uv-build>=0.9.5,<0.10" ]

[project]
name = "bump-minimum-dependencies"
version = "0.1.0"
description = "Command line tool to bump minimum dependencies in pyproject.toml"
readme = "README.md"
authors = [
  { name = "Nick Murphy", email = "namurphy@cfa.harvard.edu" },
]
requires-python = ">=3.13"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dependencies = [
  "click==8.3",
  "dep-logic>=0.5.2",
  "pyproject-parser>=0.13",
]

scripts.bump-minimum-dependencies = "bump_minimum_dependencies:main"

[dependency-groups]
dev = [
  "nox>=2026.7.11",
  "nox-uv>=0.8",
  "prek>=0.2.14",
  "pytest>=9.1",
  "pytest-freezer>=0.4.9",
  "ty>=0.0.69",
]

[tool.uv.workspace]
members = [
  "tests/data/temporary",
]
