[build-system]
build-backend = "uv_build"
requires = [ "uv-build>=0.12.3,<0.13" ]

[project]
name = "bump-minimum-dependencies"
version = "0.1.0b3"
description = "Command line tool to bump minimum dependencies in pyproject.toml"
readme = "README.md"
license-files = [ "LICENSE" ]
authors = [
  { name = "Nick Murphy", email = "namurphy@cfa.harvard.edu" },
]
requires-python = ">=3.13"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dependencies = [
  "charset-normalizer==3.3.2",
  "click>=8.4.2,<9",
  "dep-logic>=0.7.1",
  "pyproject-parser==0.14",
  "requests==2.34.2",
  "uv>=0.10",
]
urls.Source = "https://github.com/namurphy/bump-minimum-dependencies"
scripts.bump-minimum-dependencies = "bump_minimum_dependencies:main"

[dependency-groups]
dev = [
  "distlib==0.4.2",
  "nox>=2026.7.11",
  "nox-uv>=0.8",
  "prek>=0.4.12",
  "pytest==9.0.3",
  "pytest-freezer==0.4.9",
  "python-dateutil==2.8.2",
  "ty>=0.0.69",
]

[tool.uv]
workspace.members = [
  "tests/data/temporary",
]
