[project]
name = "bump-all-optionals"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = []

[project.scripts]
bump-all-optionals = "bump_all_optionals:main"

[project.optional-dependencies]
typing = [
    "mypy>0.1",
]
doc = [
    "sphinx>=1,<9",
]
test = [
    "pytest!=9.1.1",
]

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
